### PR TITLE
Add support for passing through `--gitCommit` in teamcity plugin.

### PR DESCRIPTION
**Pull request by zentron**
An additional change to update the actual embedded octo.exe will be included once that build chain has completed
image

image

### CODE REVIEW

**Review by dylanlerch — APPROVED** [review]
LGTM. I'm curious what happens when we pass through all invalid commits and whatnot but we'll cross that bridge when we come to it. 😄

**Comment by rain-on** [comment]
Is there any conditional dependency between gitref/gitcommit which should be validated on the server side (i.e. when pressing "save")?

**Comment by zentron** [comment]
> . I'm curious what happens when we pass through all invalid commits and whatnot but we'll cross that bridge when we come to it. 😄

The server will end up blowing up. Ive got another WIP around the gitref/commit validation since we should really also confirm that the commit is in the gitref tree (and that the gitref is a commit and not a tag etc)

**Comment by rain-on** [comment]
LGTM - only question - if the git commit is specified, does that override the gitref? I.e. what happens if someone has specified both fields? Is that something we should prevent when validating build step?

**Pull request merged**
